### ISSUE TITLE
Unable to find https://github.com/ChakshuGautam/stylusdb-sql/blob/main/examples/prisma/client.js

### ISSUE THREAD

**Issue by nithamitabh** [ChakshuGautam/stylusdb-sql#34]
Without the file I am unable to do my project as this package unable to be fetch with node commands, maybe it is not published in npm package.

**Comment by ChakshuGautam** [comment]
I can see the file here - https://github.com/ChakshuGautam/stylusdb-sql/blob/main/example/prisma/client.js

Not fetched through npm.
